volumes:
  ipython_history: {}
  minio_data: {}
  minio_config: {}

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h postgres -t 5 -U ${COMPOSE_PROJECT_NAME}-user || false"
      ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
